"""empty message

Revision ID: 1d4395392b01
Revises: 236c56ced6d1
Create Date: 2013-11-28 15:11:50.371152

"""

# revision identifiers, used by Alembic.
revision = '1d4395392b01'
down_revision = '236c56ced6d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('domain', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'domain')
    ### end Alembic commands ###
