"""empty message

Revision ID: 236c56ced6d1
Revises: 4337950036e5
Create Date: 2013-11-26 14:36:18.927432

"""

# revision identifiers, used by Alembic.
revision = '236c56ced6d1'
down_revision = '4337950036e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(),
                              nullable=True),
                    sa.Column('updated', sa.DateTime(),
                              nullable=True),
                    sa.Column('state', sa.Unicode(), nullable=True),
                    sa.Column('address', sa.Text(), nullable=True),
                    sa.Column('vat_addr', sa.Unicode(), nullable=True),
                    sa.Column('currency', sa.Unicode(), nullable=True),
                    sa.Column('details', sa.Text(), nullable=True),
                    sa.Column('total', sa.Float(precision=2),
                              nullable=True),
                    sa.Column('total_vat', sa.Float(precision=2),
                              nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column(u'users', sa.Column('created', sa.DateTime(),
                  nullable=True))
    op.add_column(u'users', sa.Column('updated', sa.DateTime(),
                  nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'updated')
    op.drop_column(u'users', 'created')
    op.drop_table('orders')
    ### end Alembic commands ###
